CREATE SEQUENCE IF NOT EXISTS user_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users (
   id BIGINT NOT NULL,
   username VARCHAR NOT NULL,
   password VARCHAR NOT NULL,
   email VARCHAR NOT NULL,
   role VARCHAR NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY (id),
   CONSTRAINT UC_USERS_USERNAME UNIQUE (username),
   CONSTRAINT UC_USERS_PASSWORD UNIQUE (password),
   CONSTRAINT UC_USERS_EMAIL UNIQUE (email)
);