server:
  port: 8085  # Порт, на котором запускается приложение

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/order_service_db  # URL подключения к БД PostgreSQL
    username: root  # Имя пользователя для подключения к БД
    password: root  # Пароль для подключения к БД
    driver-class-name: org.postgresql.Driver  # Драйвер JDBC для PostgreSQL

  output:
    ansi:
      enabled: ALWAYS  # Включение цветного вывода в консоли (для читаемости логов)

  jpa:
    hibernate:
      ddl-auto: validate  # Проверка схемы БД при запуске

  sql:
    init:
      mode: always  # Автоматический запуск SQL-скриптов
      schema-locations: classpath:etc/sql/schema.sql  # Путь к SQL-скрипту с DDL (создание схемы)
  #      data-locations: classpath:etc/sql/data.sql  # Путь к SQL-скрипту с начальными данными

  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"  # Адрес Kafka-брокера
      properties:
        delivery:
          timeout:
            ms: 10000  # Максимальное время доставки сообщения
          linger:
            ms: 5000  # Задержка перед отправкой (возможность отправить несколько сообщений за раз)
        request:
          timeout:
            ms: 5000  # Таймаут для запроса отправки
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5  # Максимальное количество сообщений "в полете" (без подтверждения)
        security.protocol: PLAINTEXT  # Протокол соединения (без шифрования)

      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Сериализатор для ключей сообщений
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Сериализатор значений (объекты -> JSON)
      acks: all  # Требовать подтверждение от всех брокеров (надежная доставка)

  logging:
    level:
      org:
        apache:
          kafka: INFO  # Уровень логирования Kafka
        springframework:
          kafka: INFO  # Уровень логирования Kafka в Spring

token:
  signing:
    key: PVU+sMExaAa9l8uddkUPpDT+EvcZA/hlasmXRUT9ChM=  # Ключ для подписи JWT токенов (секрет)

app:
  admin:
    username: admin  # Имя администратора, создаваемого при старте
    email: admin@gmail.com  # Email администратора
    password: admin123  # Пароль администратора

grpc:
  client:
    inventory-service:
      address: "localhost:9090"  # Адрес gRPC-сервиса инвентаризации
      negotiationType: plaintext  # Тип шифрования (в данном случае — без шифрования)