server:
  port: 8087 # Порт, на котором запускается HTTP-сервер Spring Boot

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/inventory_service_db # URL подключения к базе данных PostgreSQL
    password: root  # Пароль для подключения к базе
    username: root  # Имя пользователя для подключения к базе
    driver-class-name: org.postgresql.Driver  # Драйвер базы данных

  output:
    ansi:
      enabled: ALWAYS # Включить ANSI-коды в выводе (цветной лог)

  jpa:
    hibernate:
      ddl-auto: validate # Hibernate будет проверять соответствие схемы БД сущностям (не изменяет схему)

  sql:
    init:
      mode: always # Инициализация SQL будет запускаться всегда при старте приложения
      schema-locations: classpath:etc/sql/schema.sql # Путь к файлу SQL со схемой БД
      #data-locations: classpath:etc/sql/data.sql  # Путь к файлу с начальными данными

grpc:
  server:
    port: 9090 # Порт для gRPC-сервера
    security:
      enabled: false # Отключена безопасность (TLS) для gRPC
    name: inventory-service # Имя gRPC-сервера

